db.GuessWho.insert([
	{
		name: "paul",
		sex: "male",
		ethnicity: "black",
		eyeColour: "brown",
		glasses: "no",
		facialHair: "moustache",
		hair: "short",
		jewellery: "no",
		hairColour: "black",
		noseSize: "big",
		mouthSize: "small"
	},
	{
		name: "jody",
		sex: "female",
		ethnicity: "white",
		eyeColour: "blue",
		glasses: "no",
		facialHair: "none",
		hair: "long",
		jewellery: "yes",
		hairColour: "blonde",
		noseSize: "big",
		mouthSize: "average"
	},
	{
		name: "marcellus",
		sex: "male",
		ethnicity: "black",
		eyeColour: "brown",
		glasses: "no",
		facialHair: "goatee",
		hair: "bald",
		jewellery: "yes",
		hairColour: "none",
		noseSize: "big",
		mouthSize: "big"
	},
	{
		name: "Jimmie",
		sex: "male",
		ethnicity: "white",
		eyeColour: "brown",
		glasses: "no",
		facialHair: "none",
		hair: "short",
		jewellery: "no",
		hairColour: "brown",
		noseSize: "big",
		mouthSize: "small"
	},
	{
		name: "esmeralda",
		sex: "female",
		ethnicity: "hispanic",
		eyeColour: "brown",
		glasses: "no",
		facialHair: "none",
		hair: "long",
		jewellery: "no",
		hairColour: "brown",
		noseSize: "small",
		mouthSize: "big"
	},
	{
		name: "capitain koons",
		sex: "male",
		ethnicity: "white",
		eyeColour: "blue",
		glasses: "no",
		facialHair: "none",
		hair: "short",
		jewellery: "no",
		hairColour: "black",
		noseSize: "small",
		mouthSize: "small"
	},
	{
		name: "jules",
		sex: "male",
		ethnicity: "black",
		eyeColour: "brown",
		glasses: "no",
		facialHair: "moustache",
		hair: "short",
		jewellery: "no",
		hairColour: "black",
		noseSize: "big",
		mouthSize: "big"
	},
	{
		name: "buddy",
		sex: "male",
		ethnicity: "white",
		eyeColour: "blue",
		glasses: "no",
		facialHair: "none",
		hair: "short",
		jewellery: "no",
		hairColour: "black",
		noseSize: "small",
		mouthSize: "big"
	},
	{
		name: "the gimp",
		sex: "male",
		ethnicity: "white",
		eyeColour: "blue",
		glasses: "no",
		facialHair: "none",
		hair: "bald",
		jewellery: "no",
		hairColour: "none",
		noseSize: "big",
		mouthSize: "big"
	},
	{
		name: "yolanda",
		sex: "female",
		ethnicity: "white",
		eyeColour: "brown",
		glasses: "no",
		facialHair: "none",
		hair: "long",
		jewellery: "no",
		hairColour: "ginger",
		noseSize: "big",
		mouthSize: "average"
	},
	{
		name: "roger",
		sex: "male",
		ethnicity: "white",
		eyeColour: "brown",
		glasses: "no",
		facialHair: "none",
		hair: "long",
		jewellery: "no",
		hairColour: "blonde",
		noseSize: "big",
		mouthSize: "small"
	},
	{
		name: "fabienne",
		sex: "female",
		ethnicity: "white",
		eyeColour: "blue",
		glasses: "no",
		facialHair: "none",
		hair: "long",
		jewellery: "no",
		hairColour: "black",
		noseSize: "big",
		mouthSize: "small"
	},
	{
		name: "ringo",
		sex: "male",
		ethnicity: "white",
		eyeColour: "blue",
		glasses: "no",
		facialHair: "none",
		hair: "short",
		jewellery: "no",
		hairColour: "blonde",
		noseSize: "big",
		mouthSize: "small"
	},
	{
		name: "raquel",
		sex: "female",
		ethnicity: "white",
		eyeColour: "blue",
		glasses: "no",
		facialHair: "none",
		hair: "long",
		jewellery: "yes",
		hairColour: "ginger",
		noseSize: "small",
		mouthSize: "big"
	},
	{
		name: "lance",
		sex: "male",
		ethnicity: "white",
		eyeColour: "blue",
		glasses: "no",
		facialHair: "beard",
		hair: "long",
		jewellery: "no",
		hairColour: "ginger",
		noseSize: "small",
		mouthSize: "small"
	},
	{
		name: "butch",
		sex: "male",
		ethnicity: "white",
		eyeColour: "blue",
		glasses: "no",
		facialHair: "none",
		hair: "short",
		jewellery: "no",
		hairColour: "black",
		noseSize: "small",
		mouthSize: "small"
	},
	{
		name: "mia",
		sex: "female",
		ethnicity: "white",
		eyeColour: "blue",
		glasses: "no",
		facialHair: "none",
		hair: "long",
		jewellery: "no",
		hairColour: "black",
		noseSize: "small",
		mouthSize: "small"
	},
	{
		name: "marvin",
		sex: "male",
		ethnicity: "black",
		eyeColour: "brown",
		glasses: "no",
		facialHair: "none",
		hair: "short",
		jewellery: "no",
		hairColour: "black",
		noseSize: "big",
		mouthSize: "big"
	},
	{
		name: "zed",
		sex: "male",
		ethnicity: "white",
		eyeColour: "blue",
		glasses: "no",
		facialHair: "none",
		hair: "short",
		jewellery: "yes",
		hairColour: "blonde",
		noseSize: "big",
		mouthSize: "big"
	},
	{
		name: "brett",
		sex: "male",
		ethnicity: "white",
		eyeColour: "brown",
		glasses: "no",
		facialHair: "none",
		hair: "short",
		jewellery: "no",
		hairColour: "brown",
		noseSize: "big",
		mouthSize: "small"
	},
	{
		name: "trudi",
		sex: "female",
		ethnicity: "white",
		eyeColour: "brown",
		glasses: "no",
		facialHair: "none",
		hair: "long",
		jewellery: "no",
		hairColour: "brown",
		noseSize: "small",
		mouthSize: "small"
	},
	{
		name: "maynard",
		sex: "male",
		ethnicity: "white",
		eyeColour: "brown",
		glasses: "yes",
		facialHair: "beard",
		hair: "short",
		jewellery: "no",
		hairColour: "black",
		noseSize: "big",
		mouthSize: "big"
	},
	{
		name: "vincent",
		sex: "male",
		ethnicity: "white",
		eyeColour: "blue",
		glasses: "no",
		facialHair: "none",
		hair: "long",
		jewellery: "yes",
		hairColour: "black",
		noseSize: "big",
		mouthSize: "small"
	},
	{
		name: "winston",
		sex: "male",
		ethnicity: "white",
		eyeColour: "brown",
		glasses: "no",
		facialHair: "moustache",
		hair: "short",
		jewellery: "no",
		hairColour: "black",
		noseSize: "big",
		mouthSize: "small"
	}
]);
